export const products = [
  {
    brand: 'California Gold Nutrition',
    name: 'Vitamin D3',
    specifications: '125 mcg (5,000 IU), 360 fish gelatin softgels',
    purpose: 'Supports healthy bones and teeth immune system function.',
    images: [],
    manufacturer: 'USA',
    category: 'supplements',
    price: 25,
    productCode: '100501',
    description: 'Vitamin D is often referred to as the “sunshine vitamin” because it is produced in the skin in response to sunlight. It is an essential vitamin for many metabolic processes that help support the body. Vitamin D3 can help to regulate the absorption of calcium and phosphorus, both of which are needed for strong and healthy bones and teeth. In addition it can help support healthy immune system function.',
    reviews: [],
  },

  {
    brand: 'NOW Foods',
    name: 'Zinc',
    specifications: '50 mg, 250 tablets',
    purpose: 'Supports immune system function and enzyme functions.',
    images: [],
    manufacturer: 'USA',
    category: 'supplements',
    price: 25,
    productCode: '100502',
    description: 'Zinc is essential to the normal function of many organs and systems within the body including the skeletal, immune, neurological, and endocrine systems. Zinc is a necessary mineral co-factor for hundreds of enzymatic reactions related to protein and carbohydrate metabolism, RNA/DNA synthesis, and intercellular signaling. It is also known to play a critical role in the body\'s free radical neutralizing activities and is especially helpful for maintenance of healthy aging.',
    reviews: [],
  },

  {
    brand: 'Nature\'s Bounty',
    name: 'Calcium Magnesium Zinc with Vitamin D3',
    specifications: '5100 coated caplets',
    purpose: 'Reduce the risk of osteoporosis',
    images: [],
    manufacturer: 'USA',
    category: 'supplements',
    price: 40,
    productCode: '100503',
    description: 'Adequate Calcium and Vitamin D throughout life, as part of a well-balanced diet, may reduce the risk of osteoporosis.',
    reviews: [],
  },

  {
    brand: 'Solgar',
    name: 'Omega 3, EPA & DHA, Triple Strength',
    specifications: '950 mg, 100 softgels',
    purpose: 'Supports heart and skin health.',
    images: [],
    manufacturer: 'USA',
    category: 'supplements',
    price: 50,
    productCode: '100504',
    description: 'Omega 3 950 mg is Solgar\'s highest concentration of the natural Omega 3 polyunsaturates EPA and DHA from cold-water fish. This formulation supports cardiovascular, joint, and skin health. It is molecularly distilled to remove mercury.',
    reviews: [],
  },

  {
    brand: 'Solgar',
    name: 'Skin, Nails & Hair, Advanced MSM Formula',
    specifications: '60 tablets',
    purpose: 'Supports health of skin, hairs and nails.',
    images: [],
    manufacturer: 'USA',
    category: 'supplements',
    price: 38,
    productCode: '100505',
    description: 'Many nutrients cannot be delivered to the body externally. This formula is designed to help support collagen, a major component of skin, nails and hair that can decrease as we age. Delivering nutrients like Vitamin C and Copper internally may help support hair, nail and skin health.',
    reviews: [],
  },

  {
    brand: 'Solgar',
    name: 'Chlorella (Broken Cell-Wall)',
    specifications: '100 vegetable capsules',
    purpose: 'Correct iodine deficiency',
    images: [],
    manufacturer: 'USA',
    category: 'supplements',
    price: 29,
    productCode: '100506',
    description: 'Solgar Broken Cell-Wall Chlorella offers exceptional digestibility for maximum absorption and utilization of the single-cell algae\'s constituents.',
    reviews: [],
  },

  {
    brand: 'NOW Foods',
    name: 'Apple Cider Vinegar, Extra Strength',
    specifications: '750 mg, 180 tablets',
    purpose: 'Maintaining youth',
    images: [],
    manufacturer: 'USA',
    category: 'supplements',
    price: 15,
    productCode: '100507',
    description: 'NOW Apple Cider Vinegar is derived from the natural fermentation of sweet apple cider. Vinegar has been used worldwide for more than 2000 years for various culinary purposes. More recently, it has been recognized for its acidic properties.',
    reviews: [],
  },

  {
    brand: 'NOW Foods',
    name: 'Apple Cider Vinegar, Extra Strength',
    specifications: '750 mg, 180 tablets',
    purpose: 'Maintaining youth',
    images: [],
    manufacturer: 'USA',
    category: 'supplements',
    price: 15,
    productCode: '100507',
    description: 'NOW Apple Cider Vinegar is derived from the natural fermentation of sweet apple cider. Vinegar has been used worldwide for more than 2000 years for various culinary purposes. More recently, it has been recognized for its acidic properties.',
    reviews: [],
  },

  {
    brand: 'Mariani Dried Fruit Family',
    name: 'Probiotic Prunes',
    specifications: '198 g',
    purpose: 'Healthy food. Supports heart and bones.',
    images: [],
    manufacturer: 'USA',
    category: 'food',
    price: 3,
    productCode: '200501',
    description: 'A healthy digestive system is one of the keys overall wellness and feeling great!\n' +
      '\n' +
      'Good source of the Vitamins E, B6, B12 & Iron.\n' +
      '\n' +
      'California prunes support healthy bones and heart.',
    reviews: [],
  },

  {
    brand: 'Finn Crisp',
    name: 'Sourdough Rye Thins',
    specifications: '200 g',
    purpose: 'Healthy food.',
    images: [],
    manufacturer: 'Finland',
    category: 'food',
    price: 5,
    productCode: '200502',
    description: 'Finn Crisp Caraway is tangy sourdough, rich mellow rye and distinct caraway. Simply made for all things sizzled, chopped and sprinkled.',
    reviews: [],
  },

  {
    brand: 'Brothers-All-Natural',
    name: 'Freeze Dried Fruit Crisps, Strawberry ',
    specifications: '12 single-serve bags, 7.5 g each',
    purpose: 'Healthy food.',
    images: [],
    manufacturer: 'China',
    category: 'food',
    price: 30,
    productCode: '200503',
    description: 'Our fruit crisps are an easy, convenient and fun way to eat your fruit. The perfect anytime snack!\n' +
      '\n' +
      'We start with delicious fruit, straight from the best growing regions of the world. It is then sent directly through our state-of-the-art Freeze-Dried process that gently removes the water from the fresh fruit, transforming it into a delightfully light, and flavorful Fruit Crisp. Nothing artificial, just fruit.',
    reviews: [],
  },

  {
    brand: 'Eden Foods',
    name: 'Organic Dried Cranberries',
    specifications: '113 g',
    purpose: 'Healthy food.',
    images: [],
    manufacturer: 'Canada',
    category: 'food',
    price: 8,
    productCode: '200504',
    description: 'Whole, dried, infused with organic apple juice concentrate, and misted with organic sunflower oil to prevent clumping. Grown in Québec. Exceptional purity and taste!',
    reviews: [],
  },

  {
    brand: 'Made in Nature',
    name: 'Organic Toasted Coconut Chips, Maple Vanilla Supersnacks',
    specifications: '85 g',
    purpose: 'Healthy food.',
    images: [],
    manufacturer: 'USA',
    category: 'food',
    price: 11,
    productCode: '200505',
    description: 'Our organic Maple Vanilla Coconut Chips are, without a doubt, one of the finest couplings of flavor in all the snacks in all the countries in all the world. Ever.',
    reviews: [],
  },

  {
    brand: 'Nature\'s Wild Organic',
    name: 'Wild & Real, Organic Sliced & Dried Mango',
    specifications: '100 g',
    purpose: 'Healthy food.',
    images: [],
    manufacturer: 'USA',
    category: 'food',
    price: 11,
    productCode: '200505',
    description: 'Our organic Maple Vanilla Coconut Chips are, without a doubt, one of the finest couplings of flavor in all the snacks in all the countries in all the world. Ever.',
    reviews: [],
  },

  {
    brand: 'Barnana',
    name: 'Organic Banana Bites',
    specifications: '100 g',
    purpose: 'Healthy food.',
    images: [],
    manufacturer: 'USA',
    category: 'food',
    price: 2,
    productCode: '200506',
    description: 'Scuffed up, too ripe, oddly shaped - bananas are delicious in all their shapes and sizes.',
    reviews: [],
  },

  {
    brand: 'Noka',
    name: 'Superfood Smoothie + Prebiotic Fiber, Blueberry Beet',
    specifications: '120 g',
    purpose: 'Healthy food.',
    images: [],
    manufacturer: 'USA',
    category: 'food',
    price: 1,
    productCode: '200507',
    description: 'Purple colored foods pack powerful plant compounds, so we teamed up nutrient-dense blueberries, stamina-boosting beets and anti-aging Maqui Berry, a deep purple berry from South America, with plant protein and flax for a blend that’s as good for you as it is vibrant.',
    reviews: [],
  },

  {
    brand: 'Cetaphil',
    name: 'Daily Facial Cleanser',
    specifications: '237 ml',
    purpose: 'Facial care',
    images: [],
    manufacturer: 'Canada',
    category: 'beauty',
    price: 12,
    productCode: '300501',
    description: 'This deep cleansing, gentle foaming formula now with hydrating glycerin and B5 & B3, reinforces the skin\'s moisture barrier, balances skin and is clinically tested to remove dirt, excess oils and makeup without leaving skin dry or tight.',
    reviews: [],
  },
  {
    brand: 'Cetaphil',
    name: 'Soothing Gel Cream with Aloe',
    specifications: '85 g',
    purpose: 'Body care',
    images: [],
    manufacturer: 'USA',
    category: 'beauty',
    price: 11,
    productCode: '300502',
    description: 'Cetaphil Soothing Gel-Cream with Aloe instantly soothes, hydrates and protects dry, irritated skin with Skin Protect Allantoin. This clinically proven formula with soothing aloe vera and a unique blend of moisturizers hydrates dry skin for a full 24 hours, while restorative allantoin protects sensitive skin from environmental aggressors like wind, cold and sun. This unique, gel-cream texture absorbs quickly to provide soothing relief from dryness that leaves skin feeling hydrated and healthy.',
    reviews: [],
  },
  {
    brand: 'Cetaphil',
    name: 'Deep Hydration, Refreshing Eye Serum',
    specifications: '15 ml',
    purpose: 'Facial care',
    images: [],
    manufacturer: 'Canada',
    category: 'beauty',
    price: 9,
    productCode: '300503',
    description: 'Nourishes to deeply replenish skin\'s hydration around the eye area for 48 hours and improve the overall quality of sensitive skin. With over 70 years of sensitive skincare expertise, Cetaphil understands there is a dynamic hydration process within the skin which keeps it properly hydrated.',
    reviews: [],
  },
  {
    brand: 'Bioderma',
    name: 'Atoderm, Ultra-Soothing Balm',
    specifications: '500 ml',
    purpose: 'Body care',
    images: [],
    manufacturer: 'France',
    category: 'beauty',
    price: 40,
    productCode: '300504',
    description: 'Specially formulated for skin prone to atopy, Atoderm Intensive baume (balm) rapidly soothes feelings of itching and reduces the urge to scratch with its anti-itching active ingredient PEA. Enriched with soothing agents, it calms irritations. Atoderm Intensive baume lastingly re-establishes an effective skin barrier with the exclusive LIPGENIUM™ technology. The patented SKIN BARRIER THERAPY™ complex limits adhesion of certain bacteria (Staphylococcus aureus) to the skin surface, which can aggravate skin dryness. Immediate adsorption to get dressed quickly. Very good tolerance. Tested under dermatological supervision. Clinically-proven efficacy on irritated to atopic skin.',
    reviews: [],
  },
  {
    brand: 'Bioderma',
    name: 'Atoderm, Restorative Lip Balm',
    specifications: '15 ml',
    purpose: 'Lip care',
    images: [],
    manufacturer: 'France',
    category: 'beauty',
    price: 10,
    productCode: '300505',
    description: ' Atoderm Baume Levres (lip balm) durably moisturizes lips and isolates them from external stress. Enriched with nourishing active ingredients that replenish lipids, it instantly repairs and soothes damaged lips. The balm\'s rich texture provides extreme comfort. The applicator tip facilitates usage. Very good tolerance. Tested under dermatological supervision.',
    reviews: [],
  },
  {
    brand: 'Garnier',
    name: 'SkinActive, All-in-1 Micellar Cleansing Water, All Skin Types',
    specifications: '400 ml',
    purpose: 'Face care',
    images: [],
    manufacturer: 'USA',
    category: 'beauty',
    price: 4,
    productCode: '300506',
    description: 'Atoderm Baume Levres (lip balm) durably moisturizes lips and isolates them from external stress. Enriched with nourishing active ingredients that replenish lipids, it instantly repairs and soothes damaged lips. The balm\'s rich texture provides extreme comfort. The applicator tip facilitates usage. Very good tolerance. Tested under dermatological supervision.',
    reviews: [],
  },
  {
    brand: 'Eucerin',
    name: 'Skin Calming Itch Soothing Cream, Dry, Itchy Skin, Fragrance Free',
    specifications: '226 g',
    purpose: 'Body care',
    images: [],
    manufacturer: 'Mexico',
    category: 'beauty',
    price: 7,
    productCode: '300507',
    description: 'Eucerin with over 100 years of skin science innovation, offers a complete range of clinically proven solutions for specific skin needs, backed by a uncompromising commitment to quality. That\'s why Eucerin is recommended by Dermatologists worldwide.',
    reviews: [],
  }
]